# Generated by Django 6.1.1 on 2026-09-24 02:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField()),
                ("sleep_quality", models.SmallIntegerField()),
                ("energy", models.SmallIntegerField()),
                ("legs_feeling", models.SmallIntegerField()),
                ("breathing", models.SmallIntegerField()),
                ("pain_level", models.SmallIntegerField()),
                (
                    "notes",
                    models.TextField(
                        blank=True, null=True, verbose_name="Obersevações"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
