# Generated by Django 6.1.1 on 2026-09-24 02:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("goals", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkoutType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("slug", models.CharField(max_length=50)),
                ("color", models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name="Insights",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=20)),
                ("message", models.TextField()),
                ("value_change", models.DecimalField(decimal_places=2, max_digits=5)),
                ("generated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TrainingPlans",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                (
                    "goal_race",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="TrainingPlans",
                        to="goals.races",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Workout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Data")),
                (
                    "distance_km",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Distancia_km"
                    ),
                ),
                ("duration_sec", models.IntegerField()),
                ("pace_sec_km", models.IntegerField()),
                (
                    "speed_kmh",
                    models.DecimalField(
                        decimal_places=2, max_digits=4, verbose_name="Velocidade_kmh"
                    ),
                ),
                ("hr_avg", models.SmallIntegerField()),
                ("hr_max", models.SmallIntegerField()),
                ("cadence_spm", models.SmallIntegerField()),
                ("elavation_m", models.SmallIntegerField()),
                ("calories", models.SmallIntegerField()),
                ("rpe", models.SmallIntegerField()),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workout_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="workouts.workouttype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorkoutSplits",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("split_number", models.SmallIntegerField()),
                (
                    "distance_km",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Distancia_km"
                    ),
                ),
                ("pace_sec_km", models.IntegerField()),
                ("elavation_m", models.SmallIntegerField()),
                (
                    "workout",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="workouts.workout",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlanWorkouts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scheduled_date", models.DateTimeField()),
                ("distance_km", models.DecimalField(decimal_places=2, max_digits=5)),
                ("pace_min_sec_km", models.IntegerField()),
                ("pace_max_sec_km", models.IntegerField()),
                ("duration_sec", models.IntegerField()),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                (
                    "training_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="workouts.trainingplans",
                    ),
                ),
                (
                    "workout_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="workouts.workouttype",
                    ),
                ),
            ],
        ),
    ]
