# Generated by Django 6.1.1 on 2026-09-24 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Goals",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target_value",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="Valor da Meta"
                    ),
                ),
                (
                    "current_value",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="Valor atual"
                    ),
                ),
                ("deadline", models.DateField()),
                ("progress_pct", models.DecimalField(decimal_places=2, max_digits=5)),
                ("status", models.CharField(max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="GoalsType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("unit", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Races",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("date", models.DateTimeField()),
                ("distance_km", models.DecimalField(decimal_places=2, max_digits=5)),
                ("goal_time_sec", models.IntegerField()),
                ("place", models.CharField(max_length=20)),
                ("notes", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="RaceType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("distance_km", models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
