# Generated by Django 6.1.1 on 2026-09-24 02:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("goals", "0001_initial"),
        ("workouts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="goals",
            name="goal_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="workouts.workouttype"
            ),
        ),
        migrations.AddField(
            model_name="goals",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="goals",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="races",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="races",
            name="race_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="goals.racetype"
            ),
        ),
    ]
